import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Alert from "./components/alert";
import Stepper from "./components/stepper";
import parameters from "../personalization/parameters.json";
import FormComponent from "./components/Form";

const Home: NextPage = () => {
  const [openInitialModal, setOpenInitialModal] = useState<boolean>(true);
  const [currentStep, setCurrentStep] = useState<number>(1);

  const steps = parameters.steps;

  const initialAlert = {
    title: "Indicaciones",
    messages: [
      "1. Los campos marcados con asterisco (*) son obligatorios y deben ser llenados para enviar la solicitud.",
      "2. Debe habilitar las ventanas emergentes en su navegador para visualizar la impresión del formulario de su solicitud.",
    ],
  };

  return (
    <>
      <Head>
        <title>Solicitud de Empleo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Alert
        data-modal-toggle={"defaultModal"}
        setClose={() => {
          setOpenInitialModal(false);
        }}
        open={openInitialModal}
        title={initialAlert.title}
        messages={initialAlert.messages}
      />

      {/* Navbar Personalizable */}
      <div className="w-full justify-between lg:flex">
        <img className="w-16 lg:w-32" src={"/Logo.png"} alt="Logo" />
        <div className="w-full">
          <Stepper steps={steps} currentStep={currentStep} />
        </div>
      </div>

      <main className="container mx-auto flex min-h-screen flex-col items-center p-4">
        <h1
          className={`pt-4 text-2xl font-semibold text-[color:var(--fontColor)] lg:pt-8`}
        >
          Solicitud Empleo {parameters.company}
        </h1>
        <p className="max-w-[288px] pb-8 text-sm text-gray-500">
          Llene los datos para completar su solicitud de empleo. Necesitará su
          cédula o pasaporte.
        </p>

        {/* Form Component */}

        <FormComponent step={currentStep} setCurrentStep={setCurrentStep} />

        {/* {nacionalidades?.data?.map(nacionalidad=>{
          if(nacionalidad.Codigo>0)
          return <p className="">{nacionalidad.Descripcion}</p>
        })} */}
      </main>
    </>
  );
};

export default Home;
