import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import { trpc } from "../utils/trpc";
import Alert from "./components/alert";

const Home: NextPage = () => {
  
  const nacionalidades = trpc.formOptions.getAllNationalities.useQuery();
  const [openInitialModal, setOpenInitialModal] = useState<boolean>(true)

  const initialAlert = {
    title: "Indicaciones",
    messages: [
      "1. Los campos marcados con asterisco (*) son obligatorios y deben ser llenados para enviar la solicitud.",
      "2. Debe habilitar las ventanas emergentes en su navegador para visualizar la impresión del formulario de su solicitud."
    ]
  }
  

  return (
    <>
      <Head>
        <title>Solicitud de Empleo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Alert data-modal-toggle={"defaultModal"} 
       setClose={()=>{setOpenInitialModal(false)}} 
       open={openInitialModal} 
       title={initialAlert.title} 
       messages={initialAlert.messages} 
        />

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
       
        <h1 className="text-2xl font-semibold">Solicitud Empleo SPN</h1>
        {nacionalidades?.data?.map(nacionalidad=>{
          if(nacionalidad.Codigo>0)
          return <p>{nacionalidad.Descripcion}</p>
        })}
      </main>
    </>
  );
};

export default Home;


